# Python的asyncio并发编程

Python的asyncio并发编程

在之前的文章中，我们介绍了Python的多线程和多进程并发编程，今天，我们来用Python中的asyncio实现协程并发编程。

asyncio可以并发地运行Python协程，协程是是非抢占式的一个函数，可以在遇到IO时让出CPU给其他协程执行，占用资源比线程小很多，协程的切换也没有线程的开销大。Python的协程是通过asyncio这个库来调用的。

Python在3.4的版本中引入了协程的概念，并在之后的版本中不断改进，也随着版本的更新用法也发生了变化，本篇文章基于目前最新的Python3.7版本来讲解。

#### 协程

定义一个协程并运行

```python
import asyncio

async def main():
    print('I am')
    await asyncio.sleep(1)
    print('Xiaohei!')

asyncio.run(main())
```

定义一个协程非常简单，只需要在普通函数前加一个async关键字就可以了。然后在遇到IO或者其他不占用CPU的操作时可以使用await让出CPU执行权。当一个函数边加上async时，它就不能像函数调用那样调用了，必须以协程的方式调用，比如上面的程序使用asyncio.run()运行协程。

asyncio.sleep()函数可以让协程检出CPU执行权，并在指定的时间后重新调度。

asyncio.run()函数可以运行传入的协程，并在协程运行完成后结束程序，是asyncio程序的入口。

#### 任务

asyncio.create_task()可以将一个协程对象包装成一个任务，一个任务可以自动被Python调度运行。

```python
import asyncio
import time

async def hello():
    print("hello!")

async def main():
    task = asyncio.create_task(hello())
    await task

asyncio.run(main())
```


#### Future

Future对象是一种特殊的低层级可等待的对象，表示一个异步操作的最终结果，协程可以等待 Future 对象直到它们有结果或发生异常或被取消。


**协程、任务和Future对象都是可等待的对象，可以用在await语句中**


asyncio.as_completed(aws, *, loop=None, timeout=None):

可以将一个协程集合包装成一个Future对象的集合。

```python
import asyncio
import time
import random

async def hello(second):
    await asyncio.sleep(second)
    print("sleep: {}".format(second))
    return second

async def main():
    tasks = []
    for i in range(10):
        task = asyncio.create_task(hello(random.randint(1,5)))
        tasks.append(task)
    for t in asyncio.as_completed(tasks):
        result = await t
        print(result)

asyncio.run(main())
```

**asyncio.as_completed()函数返回的结果是无序的，哪个对象先运行完成先返回哪个**

asyncio.gather(*aws, loop=None, return_exceptions=False)
可以并发运行aws中的可等待对象，等aws中的对象都运行完成时返回所有对象的结果集合组成的列表，顺序和aws中的对象的顺序一致。

return_exceptions默认为False，异常会终止程序，如果return_exceptions为True，则如果某个对象发生了异常，其他对象还是可以正常运行的，异常的那个对象的返回结果是引发的异常。


```python
import asyncio
import time
import random

async def div(x, y):
    return x / y

async def main():
    tasks = []
    res = await asyncio.gather(
        div(1, 2),
        div(2, 0),
        div(8, 4),
        return_exceptions=True
    )
    print(res)

asyncio.run(main())
```

运行结果：
```
[0.5, ZeroDivisionError('division by zero'), 2.0]
```

关于asyncio的使用就介绍到这里，平时使用asyncio比较常用的就是这些，如果想要深入了解asyncio的更多用法可以参考Python官方的文档。


参考资料：https://docs.python.org/3/library/asyncio-task.html
